name: "📚 Blog Updater"

on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: Hashnode Blog
        uses: varunsridharan/action-hashnode-blog@1.1.1

        with:
          USERNAME: 'pranshujha' # Hashnode Username
          BLOG_URL: 'https://pranshujha.hashnode.dev/' # Blog URL
          COUNT: 3 # MAX Visisble
          STYLE: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
